### ISSUE TITLE
Nova LLDB Integration/Collaboration

### ISSUE THREAD

**Issue by chances** [staysail/nova-cdragon#6]
In my free time, I'm working on a generic extension to integrate the LLVM debugger via the DAP provided in lldb-vscode, [nova-lldb](https://github.com/snow-developments/nova-lldb#readme). It could be beneficial to my extension if I borrow ideas from here, with full attribution of course.

Considering the further progress of this extension's LLDB integration, what are your thoughts on some sort of cross-project collaboration?

**Comment by gdamore** [comment]
It looks like the Nova folks have a better (first-party) implementation based on Apple's LLDB.framework.  Their extension is called Icarus, but I haven't tested it out yet.
