### ISSUE TITLE
Specify project specific includes/libs paths

### ISSUE THREAD

**Issue by nyteshade** [staysail/nova-cdragon#7]
Rather than having errors show up where unresolved headers are indicated, allow the programmer to have a way to specify where the headers exists in an equivalent of a -I directory. Additionally allow lib location if it helps for the equivalent of -L entries.

**Comment by gdamore** [comment]
This is mostly an issue for `clangd` and it has a standard way of doing this.  Google for `compile_commands.json` to find out more data -- CMake can generate this for you btw.

**Comment by gdamore** [comment]
I'm closing this for now -- clangd does its own thing here, and that's `compile_commands.json` which should be generated via CMake, but there are other ways to do so as well.
